name: quantum_care
description: >
  Quantum Care is a Flutter-based healthcare application developed as part of a
  final year project. The app focuses on providing a smart, user-friendly
  platform for health monitoring and management using modern UI principles.

# Prevents publishing to pub.dev
publish_to: "none"

# Version format: major.minor.patch+build
# Increment build number on each release
version: 1.1.0+2

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/animations/Health.json
